coverage:
  precision: 2
  round: down
  range: "70...95"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/*_test.py"
  - "**/test_*.py"
  - "third_party/**/*"
  - "opendbc/**/*"
  - "panda/**/*"
  - "cereal/**/*"
  - "msgq/**/*"
  - "rednose/**/*"
  - "tinygrad/**/*"
  - "teleoprtc/**/*"
  - "**/SConscript"
  - "SConstruct"
